name:                flicker
version:             0.1.0.0
github:              "talanie85/flicker"
license:             BSD3
author:              "Philip Kranz"
maintainer:          "pk@pmlk.net"
copyright:           "2021 Philip Kranz"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Display flicker codes for chipTAN systems.
description:         Please see the README on GitHub at <https://github.com/talanis85/flicker#readme>

dependencies:
- base >= 4.7 && < 5
- disguise-gtk

executables:
  flicker:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flicker

tests:
  flicker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flicker
